// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/insync.proto

package insync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncMode int32

const (
	SyncMode_BASE_SYNC SyncMode = 0
	SyncMode_FULL_SYNC SyncMode = 1
)

// Enum value maps for SyncMode.
var (
	SyncMode_name = map[int32]string{
		0: "BASE_SYNC",
		1: "FULL_SYNC",
	}
	SyncMode_value = map[string]int32{
		"BASE_SYNC": 0,
		"FULL_SYNC": 1,
	}
)

func (x SyncMode) Enum() *SyncMode {
	p := new(SyncMode)
	*p = x
	return p
}

func (x SyncMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_insync_proto_enumTypes[0].Descriptor()
}

func (SyncMode) Type() protoreflect.EnumType {
	return &file_api_proto_insync_proto_enumTypes[0]
}

func (x SyncMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncMode.Descriptor instead.
func (SyncMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{0}
}

type GetAuthURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthURLRequest) Reset() {
	*x = GetAuthURLRequest{}
	mi := &file_api_proto_insync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthURLRequest) ProtoMessage() {}

func (x *GetAuthURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthURLRequest.ProtoReflect.Descriptor instead.
func (*GetAuthURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{0}
}

type GetAuthURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthURLResponse) Reset() {
	*x = GetAuthURLResponse{}
	mi := &file_api_proto_insync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthURLResponse) ProtoMessage() {}

func (x *GetAuthURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthURLResponse.ProtoReflect.Descriptor instead.
func (*GetAuthURLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthCode      string                 `protobuf:"bytes,1,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"` // Simplificação para o fluxo OAuth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountRequest) Reset() {
	*x = AddAccountRequest{}
	mi := &file_api_proto_insync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountRequest) ProtoMessage() {}

func (x *AddAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountRequest.ProtoReflect.Descriptor instead.
func (*AddAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{2}
}

func (x *AddAccountRequest) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

type AddAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccountResponse) Reset() {
	*x = AddAccountResponse{}
	mi := &file_api_proto_insync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountResponse) ProtoMessage() {}

func (x *AddAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountResponse.ProtoReflect.Descriptor instead.
func (*AddAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{3}
}

func (x *AddAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddAccountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ConfigureSyncRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	LocalPath      string                 `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RemoteFolderId string                 `protobuf:"bytes,3,opt,name=remote_folder_id,json=remoteFolderId,proto3" json:"remote_folder_id,omitempty"`
	Mode           SyncMode               `protobuf:"varint,4,opt,name=mode,proto3,enum=insync.SyncMode" json:"mode,omitempty"`
	IsDirectory    bool                   `protobuf:"varint,5,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	DisplayName    string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureSyncRequest) Reset() {
	*x = ConfigureSyncRequest{}
	mi := &file_api_proto_insync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureSyncRequest) ProtoMessage() {}

func (x *ConfigureSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureSyncRequest.ProtoReflect.Descriptor instead.
func (*ConfigureSyncRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureSyncRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ConfigureSyncRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *ConfigureSyncRequest) GetRemoteFolderId() string {
	if x != nil {
		return x.RemoteFolderId
	}
	return ""
}

func (x *ConfigureSyncRequest) GetMode() SyncMode {
	if x != nil {
		return x.Mode
	}
	return SyncMode_BASE_SYNC
}

func (x *ConfigureSyncRequest) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *ConfigureSyncRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ConfigureSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureSyncResponse) Reset() {
	*x = ConfigureSyncResponse{}
	mi := &file_api_proto_insync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureSyncResponse) ProtoMessage() {}

func (x *ConfigureSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureSyncResponse.ProtoReflect.Descriptor instead.
func (*ConfigureSyncResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigureSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureSyncResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SyncStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStatusRequest) Reset() {
	*x = SyncStatusRequest{}
	mi := &file_api_proto_insync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatusRequest) ProtoMessage() {}

func (x *SyncStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatusRequest.ProtoReflect.Descriptor instead.
func (*SyncStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{6}
}

type SyncStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FilePath           string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // e.g., "Uploading", "Downloading", "Synced", "Error"
	ProgressPercentage int32                  `protobuf:"varint,3,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	TotalSize          int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	ProcessedSize      int64                  `protobuf:"varint,5,opt,name=processed_size,json=processedSize,proto3" json:"processed_size,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncStatusResponse) Reset() {
	*x = SyncStatusResponse{}
	mi := &file_api_proto_insync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatusResponse) ProtoMessage() {}

func (x *SyncStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatusResponse.ProtoReflect.Descriptor instead.
func (*SyncStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{7}
}

func (x *SyncStatusResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SyncStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SyncStatusResponse) GetProgressPercentage() int32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *SyncStatusResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *SyncStatusResponse) GetProcessedSize() int64 {
	if x != nil {
		return x.ProcessedSize
	}
	return 0
}

type ListFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID da pasta remota (ex.: "root" no Google Drive).
	FolderPath string `protobuf:"bytes,1,opt,name=folder_path,json=folderPath,proto3" json:"folder_path,omitempty"`
	// Conta autenticada retornada por AddAccount; obrigatório para listar na nuvem.
	AccountId     string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_api_proto_insync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{8}
}

func (x *ListFilesRequest) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

func (x *ListFilesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsDirectory   bool                   `protobuf:"varint,3,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	LastModified  string                 `protobuf:"bytes,5,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	Etag          string                 `protobuf:"bytes,6,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_api_proto_insync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{9}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

func (x *FileInfo) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_api_proto_insync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{10}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type SyncedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          SyncMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=insync.SyncMode" json:"mode,omitempty"`
	LocalPath     string                 `protobuf:"bytes,3,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncedFile) Reset() {
	*x = SyncedFile{}
	mi := &file_api_proto_insync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncedFile) ProtoMessage() {}

func (x *SyncedFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncedFile.ProtoReflect.Descriptor instead.
func (*SyncedFile) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{11}
}

func (x *SyncedFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SyncedFile) GetMode() SyncMode {
	if x != nil {
		return x.Mode
	}
	return SyncMode_BASE_SYNC
}

func (x *SyncedFile) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

type ListSyncedFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncedFilesRequest) Reset() {
	*x = ListSyncedFilesRequest{}
	mi := &file_api_proto_insync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncedFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncedFilesRequest) ProtoMessage() {}

func (x *ListSyncedFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncedFilesRequest.ProtoReflect.Descriptor instead.
func (*ListSyncedFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{12}
}

func (x *ListSyncedFilesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListSyncedFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*SyncedFile          `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncedFilesResponse) Reset() {
	*x = ListSyncedFilesResponse{}
	mi := &file_api_proto_insync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncedFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncedFilesResponse) ProtoMessage() {}

func (x *ListSyncedFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_insync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncedFilesResponse.ProtoReflect.Descriptor instead.
func (*ListSyncedFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_insync_proto_rawDescGZIP(), []int{13}
}

func (x *ListSyncedFilesResponse) GetFiles() []*SyncedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_api_proto_insync_proto protoreflect.FileDescriptor

const file_api_proto_insync_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/insync.proto\x12\x06insync\"\x13\n" +
	"\x11GetAuthURLRequest\"&\n" +
	"\x12GetAuthURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"0\n" +
	"\x11AddAccountRequest\x12\x1b\n" +
	"\tauth_code\x18\x01 \x01(\tR\bauthCode\"r\n" +
	"\x12AddAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xea\x01\n" +
	"\x14ConfigureSyncRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"local_path\x18\x02 \x01(\tR\tlocalPath\x12(\n" +
	"\x10remote_folder_id\x18\x03 \x01(\tR\x0eremoteFolderId\x12$\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x10.insync.SyncModeR\x04mode\x12!\n" +
	"\fis_directory\x18\x05 \x01(\bR\visDirectory\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\"V\n" +
	"\x15ConfigureSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x13\n" +
	"\x11SyncStatusRequest\"\xc0\x01\n" +
	"\x12SyncStatusResponse\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12/\n" +
	"\x13progress_percentage\x18\x03 \x01(\x05R\x12progressPercentage\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12%\n" +
	"\x0eprocessed_size\x18\x05 \x01(\x03R\rprocessedSize\"R\n" +
	"\x10ListFilesRequest\x12\x1f\n" +
	"\vfolder_path\x18\x01 \x01(\tR\n" +
	"folderPath\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"\xa2\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\fis_directory\x18\x03 \x01(\bR\visDirectory\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12#\n" +
	"\rlast_modified\x18\x05 \x01(\tR\flastModified\x12\x12\n" +
	"\x04etag\x18\x06 \x01(\tR\x04etag\";\n" +
	"\x11ListFilesResponse\x12&\n" +
	"\x05files\x18\x01 \x03(\v2\x10.insync.FileInfoR\x05files\"e\n" +
	"\n" +
	"SyncedFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12$\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x10.insync.SyncModeR\x04mode\x12\x1d\n" +
	"\n" +
	"local_path\x18\x03 \x01(\tR\tlocalPath\"7\n" +
	"\x16ListSyncedFilesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"C\n" +
	"\x17ListSyncedFilesResponse\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.insync.SyncedFileR\x05files*(\n" +
	"\bSyncMode\x12\r\n" +
	"\tBASE_SYNC\x10\x00\x12\r\n" +
	"\tFULL_SYNC\x10\x012\xc7\x03\n" +
	"\rInsyncService\x12C\n" +
	"\n" +
	"GetAuthURL\x12\x19.insync.GetAuthURLRequest\x1a\x1a.insync.GetAuthURLResponse\x12C\n" +
	"\n" +
	"AddAccount\x12\x19.insync.AddAccountRequest\x1a\x1a.insync.AddAccountResponse\x12L\n" +
	"\rConfigureSync\x12\x1c.insync.ConfigureSyncRequest\x1a\x1d.insync.ConfigureSyncResponse\x12H\n" +
	"\rGetSyncStatus\x12\x19.insync.SyncStatusRequest\x1a\x1a.insync.SyncStatusResponse0\x01\x12@\n" +
	"\tListFiles\x12\x18.insync.ListFilesRequest\x1a\x19.insync.ListFilesResponse\x12R\n" +
	"\x0fListSyncedFiles\x12\x1e.insync.ListSyncedFilesRequest\x1a\x1f.insync.ListSyncedFilesResponseB4Z2github.com/thiagohmm/insync-clone/api/proto/insyncb\x06proto3"

var (
	file_api_proto_insync_proto_rawDescOnce sync.Once
	file_api_proto_insync_proto_rawDescData []byte
)

func file_api_proto_insync_proto_rawDescGZIP() []byte {
	file_api_proto_insync_proto_rawDescOnce.Do(func() {
		file_api_proto_insync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_insync_proto_rawDesc), len(file_api_proto_insync_proto_rawDesc)))
	})
	return file_api_proto_insync_proto_rawDescData
}

var file_api_proto_insync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_insync_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_insync_proto_goTypes = []any{
	(SyncMode)(0),                   // 0: insync.SyncMode
	(*GetAuthURLRequest)(nil),       // 1: insync.GetAuthURLRequest
	(*GetAuthURLResponse)(nil),      // 2: insync.GetAuthURLResponse
	(*AddAccountRequest)(nil),       // 3: insync.AddAccountRequest
	(*AddAccountResponse)(nil),      // 4: insync.AddAccountResponse
	(*ConfigureSyncRequest)(nil),    // 5: insync.ConfigureSyncRequest
	(*ConfigureSyncResponse)(nil),   // 6: insync.ConfigureSyncResponse
	(*SyncStatusRequest)(nil),       // 7: insync.SyncStatusRequest
	(*SyncStatusResponse)(nil),      // 8: insync.SyncStatusResponse
	(*ListFilesRequest)(nil),        // 9: insync.ListFilesRequest
	(*FileInfo)(nil),                // 10: insync.FileInfo
	(*ListFilesResponse)(nil),       // 11: insync.ListFilesResponse
	(*SyncedFile)(nil),              // 12: insync.SyncedFile
	(*ListSyncedFilesRequest)(nil),  // 13: insync.ListSyncedFilesRequest
	(*ListSyncedFilesResponse)(nil), // 14: insync.ListSyncedFilesResponse
}
var file_api_proto_insync_proto_depIdxs = []int32{
	0,  // 0: insync.ConfigureSyncRequest.mode:type_name -> insync.SyncMode
	10, // 1: insync.ListFilesResponse.files:type_name -> insync.FileInfo
	0,  // 2: insync.SyncedFile.mode:type_name -> insync.SyncMode
	12, // 3: insync.ListSyncedFilesResponse.files:type_name -> insync.SyncedFile
	1,  // 4: insync.InsyncService.GetAuthURL:input_type -> insync.GetAuthURLRequest
	3,  // 5: insync.InsyncService.AddAccount:input_type -> insync.AddAccountRequest
	5,  // 6: insync.InsyncService.ConfigureSync:input_type -> insync.ConfigureSyncRequest
	7,  // 7: insync.InsyncService.GetSyncStatus:input_type -> insync.SyncStatusRequest
	9,  // 8: insync.InsyncService.ListFiles:input_type -> insync.ListFilesRequest
	13, // 9: insync.InsyncService.ListSyncedFiles:input_type -> insync.ListSyncedFilesRequest
	2,  // 10: insync.InsyncService.GetAuthURL:output_type -> insync.GetAuthURLResponse
	4,  // 11: insync.InsyncService.AddAccount:output_type -> insync.AddAccountResponse
	6,  // 12: insync.InsyncService.ConfigureSync:output_type -> insync.ConfigureSyncResponse
	8,  // 13: insync.InsyncService.GetSyncStatus:output_type -> insync.SyncStatusResponse
	11, // 14: insync.InsyncService.ListFiles:output_type -> insync.ListFilesResponse
	14, // 15: insync.InsyncService.ListSyncedFiles:output_type -> insync.ListSyncedFilesResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_insync_proto_init() }
func file_api_proto_insync_proto_init() {
	if File_api_proto_insync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_insync_proto_rawDesc), len(file_api_proto_insync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_insync_proto_goTypes,
		DependencyIndexes: file_api_proto_insync_proto_depIdxs,
		EnumInfos:         file_api_proto_insync_proto_enumTypes,
		MessageInfos:      file_api_proto_insync_proto_msgTypes,
	}.Build()
	File_api_proto_insync_proto = out.File
	file_api_proto_insync_proto_goTypes = nil
	file_api_proto_insync_proto_depIdxs = nil
}
