// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/proto/insync.proto

package insync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InsyncService_GetAuthURL_FullMethodName    = "/insync.InsyncService/GetAuthURL"
	InsyncService_AddAccount_FullMethodName    = "/insync.InsyncService/AddAccount"
	InsyncService_ConfigureSync_FullMethodName = "/insync.InsyncService/ConfigureSync"
	InsyncService_GetSyncStatus_FullMethodName = "/insync.InsyncService/GetSyncStatus"
	InsyncService_ListFiles_FullMethodName     = "/insync.InsyncService/ListFiles"
)

// InsyncServiceClient is the client API for InsyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InsyncServiceClient interface {
	// Configurações enviadas do CLI para o Daemon
	GetAuthURL(ctx context.Context, in *GetAuthURLRequest, opts ...grpc.CallOption) (*GetAuthURLResponse, error)
	AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*AddAccountResponse, error)
	ConfigureSync(ctx context.Context, in *ConfigureSyncRequest, opts ...grpc.CallOption) (*ConfigureSyncResponse, error)
	// Acompanhamento de status em tempo real
	GetSyncStatus(ctx context.Context, in *SyncStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncStatusResponse], error)
	// Listagem de arquivos
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
}

type insyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInsyncServiceClient(cc grpc.ClientConnInterface) InsyncServiceClient {
	return &insyncServiceClient{cc}
}

func (c *insyncServiceClient) GetAuthURL(ctx context.Context, in *GetAuthURLRequest, opts ...grpc.CallOption) (*GetAuthURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthURLResponse)
	err := c.cc.Invoke(ctx, InsyncService_GetAuthURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insyncServiceClient) AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*AddAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAccountResponse)
	err := c.cc.Invoke(ctx, InsyncService_AddAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insyncServiceClient) ConfigureSync(ctx context.Context, in *ConfigureSyncRequest, opts ...grpc.CallOption) (*ConfigureSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureSyncResponse)
	err := c.cc.Invoke(ctx, InsyncService_ConfigureSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insyncServiceClient) GetSyncStatus(ctx context.Context, in *SyncStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InsyncService_ServiceDesc.Streams[0], InsyncService_GetSyncStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncStatusRequest, SyncStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsyncService_GetSyncStatusClient = grpc.ServerStreamingClient[SyncStatusResponse]

func (c *insyncServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, InsyncService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsyncServiceServer is the server API for InsyncService service.
// All implementations must embed UnimplementedInsyncServiceServer
// for forward compatibility.
type InsyncServiceServer interface {
	// Configurações enviadas do CLI para o Daemon
	GetAuthURL(context.Context, *GetAuthURLRequest) (*GetAuthURLResponse, error)
	AddAccount(context.Context, *AddAccountRequest) (*AddAccountResponse, error)
	ConfigureSync(context.Context, *ConfigureSyncRequest) (*ConfigureSyncResponse, error)
	// Acompanhamento de status em tempo real
	GetSyncStatus(*SyncStatusRequest, grpc.ServerStreamingServer[SyncStatusResponse]) error
	// Listagem de arquivos
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	mustEmbedUnimplementedInsyncServiceServer()
}

// UnimplementedInsyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInsyncServiceServer struct{}

func (UnimplementedInsyncServiceServer) GetAuthURL(context.Context, *GetAuthURLRequest) (*GetAuthURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthURL not implemented")
}
func (UnimplementedInsyncServiceServer) AddAccount(context.Context, *AddAccountRequest) (*AddAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAccount not implemented")
}
func (UnimplementedInsyncServiceServer) ConfigureSync(context.Context, *ConfigureSyncRequest) (*ConfigureSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureSync not implemented")
}
func (UnimplementedInsyncServiceServer) GetSyncStatus(*SyncStatusRequest, grpc.ServerStreamingServer[SyncStatusResponse]) error {
	return status.Error(codes.Unimplemented, "method GetSyncStatus not implemented")
}
func (UnimplementedInsyncServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedInsyncServiceServer) mustEmbedUnimplementedInsyncServiceServer() {}
func (UnimplementedInsyncServiceServer) testEmbeddedByValue()                       {}

// UnsafeInsyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InsyncServiceServer will
// result in compilation errors.
type UnsafeInsyncServiceServer interface {
	mustEmbedUnimplementedInsyncServiceServer()
}

func RegisterInsyncServiceServer(s grpc.ServiceRegistrar, srv InsyncServiceServer) {
	// If the following call panics, it indicates UnimplementedInsyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InsyncService_ServiceDesc, srv)
}

func _InsyncService_GetAuthURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsyncServiceServer).GetAuthURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsyncService_GetAuthURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsyncServiceServer).GetAuthURL(ctx, req.(*GetAuthURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsyncService_AddAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsyncServiceServer).AddAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsyncService_AddAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsyncServiceServer).AddAccount(ctx, req.(*AddAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsyncService_ConfigureSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsyncServiceServer).ConfigureSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsyncService_ConfigureSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsyncServiceServer).ConfigureSync(ctx, req.(*ConfigureSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsyncService_GetSyncStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InsyncServiceServer).GetSyncStatus(m, &grpc.GenericServerStream[SyncStatusRequest, SyncStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsyncService_GetSyncStatusServer = grpc.ServerStreamingServer[SyncStatusResponse]

func _InsyncService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsyncServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsyncService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsyncServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InsyncService_ServiceDesc is the grpc.ServiceDesc for InsyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InsyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insync.InsyncService",
	HandlerType: (*InsyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthURL",
			Handler:    _InsyncService_GetAuthURL_Handler,
		},
		{
			MethodName: "AddAccount",
			Handler:    _InsyncService_AddAccount_Handler,
		},
		{
			MethodName: "ConfigureSync",
			Handler:    _InsyncService_ConfigureSync_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _InsyncService_ListFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSyncStatus",
			Handler:       _InsyncService_GetSyncStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/insync.proto",
}
